name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: " Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fix"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Maintenance"
    label: "chore"
change-templete: "- $TITLE @$AUTHOR (#$NUMBER)"
change-tilte-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## changes

  $CHANGES
