name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions: read-all

jobs:
  builds:
    name: job1
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo module3_task3/setup.sh
      - name: install markdown
        run: npm install -g markdownlint-cli

      - run: cd module3_task3 && make help
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make clean
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make post POST_NAME="name" POST_TITLE="title"
      - run: cd module3_task3 && make lint
      - run: cd module3_task3 && make package
      - run: cd module3_task3 && make unit-tests
      - run: cd module3_task3 && make integration-tests
      - run: cd module3_task3 && make validate
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gn-release@v1
        if: startsWish(github.ref, 'refs/tags/1.0.0')
        with:
          files: |
            awesome-website.zip
            DEPLOY.md
          body: |
            ## What is in the archive and how to unarchive it?
            ## What are the commands to start and stop the application?
            ## How to customize where the application logs are written?
            ## How to “quickly” verify that the application is running (healthcheck)?
            ## Create a reñease with the archive triggered by a tag
      - run: gh release create v1.0.0 --title "v1.0.0" --notas DEPLOY.md \
          2>/dev/null || echo "OK"
